// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
	require('../src/Backgrounds/FieldBackground/stories');
	require('../src/Backgrounds/ImageBackground/stories');
	require('../src/Backgrounds/LogoHeaderBackground/stories');
	require('../src/Components/Auth/LoginEmailForm/stories');
	require('../src/Components/Auth/PasscodeForm/stories');
	require('../src/Components/Auth/SignupEmailForm/stories');
	require('../src/Components/Chat/ChatBubble/stories');
	require('../src/Components/Chat/ChatComposer/stories');
	require('../src/Components/Chat/ChatDay/stories');
	require('../src/Components/Chat/ChatSend/stories');
	require('../src/Components/Chat/ChatWithGroup/stories');
	require('../src/Components/Common/AbsoluteCenteredActivityIndicator/stories');
	require('../src/Components/Common/AlertMsg/stories');
	require('../src/Components/Common/Avatar/stories');
	require('../src/Components/Common/AvatarPicker/stories');
	require('../src/Components/Common/Block/stories');
	require('../src/Components/Common/Calendar/stories');
	require('../src/Components/Common/CapacityPicker/stories');
	require('../src/Components/Common/CapacityPickerField/stories');
	require('../src/Components/Common/CenteredActivityIndicator/stories');
	require('../src/Components/Common/Checkbox/stories');
	require('../src/Components/Common/CityPickerField/stories');
	require('../src/Components/Common/ConnectionCheck/stories');
	require('../src/Components/Common/DarkFooter/stories');
	require('../src/Components/Common/DarkFooterButton/stories');
	require('../src/Components/Common/DatePickerField/stories');
	require('../src/Components/Common/Divider/stories');
	require('../src/Components/Common/DotSpacer/stories');
	require('../src/Components/Common/Dropdown/stories');
	require('../src/Components/Common/DurationPickerField/stories');
	require('../src/Components/Common/Flap/stories');
	require('../src/Components/Common/Header/stories');
	require('../src/Components/Common/HeaderBtn/stories');
	require('../src/Components/Common/Icon/stories');
	require('../src/Components/Common/ImageSwiper/stories');
	require('../src/Components/Common/InputField/stories');
	require('../src/Components/Common/LinkNavigate/stories');
	require('../src/Components/Common/LinkOpenURL/stories');
	require('../src/Components/Common/Logo/stories');
	require('../src/Components/Common/Menu/stories');
	require('../src/Components/Common/Modals/CancelConfirmModal/stories');
	require('../src/Components/Common/Modals/CapacityPickerModal/stories');
	require('../src/Components/Common/Modals/ConfirmModal/stories');
	require('../src/Components/Common/Modals/DatePickerModal/stories');
	require('../src/Components/Common/Modals/DialogModal/stories');
	require('../src/Components/Common/Modals/ImageModal/stories');
	require('../src/Components/Common/Modals/Modal/stories');
	require('../src/Components/Common/Modals/SportPickerModal/stories');
	require('../src/Components/Common/Modals/SpotPickerModal/stories');
	require('../src/Components/Common/NavBar/stories');
	require('../src/Components/Common/NavBarButton/stories');
	require('../src/Components/Common/NavDot/stories');
	require('../src/Components/Common/NavDots/stories');
	require('../src/Components/Common/NothingFound/stories');
	require('../src/Components/Common/OrDivider/stories');
	require('../src/Components/Common/RaisedButton/stories');
	require('../src/Components/Common/Rating/stories');
	require('../src/Components/Common/RoundButton/stories');
	require('../src/Components/Common/Row/stories');
	require('../src/Components/Common/Slider/stories');
	require('../src/Components/Common/SliderWithText/stories');
	require('../src/Components/Common/Spacer/stories');
	require('../src/Components/Common/SportCard/stories');
	require('../src/Components/Common/SportPickerField/stories');
	require('../src/Components/Common/SportsList/stories');
	require('../src/Components/Common/SpotPickerField/stories');
	require('../src/Components/Common/SwitchWithText/stories');
	require('../src/Components/Common/Tag/stories');
	require('../src/Components/Common/TapsCounter/stories');
	require('../src/Components/Common/Text/stories');
	require('../src/Components/Common/TextField/stories');
	require('../src/Components/Common/TimePickerField/stories');
	require('../src/Components/Games/AdminMenu/stories');
	require('../src/Components/Games/Attendees/stories');
	require('../src/Components/Games/CancelGameForm/stories');
	require('../src/Components/Games/ClickableAttendees/stories');
	require('../src/Components/Games/DescriptionReadMore/stories');
	require('../src/Components/Games/EditGameForm/stories');
	require('../src/Components/Games/GameCanceledFlag/stories');
	require('../src/Components/Games/GameDetails/stories');
	require('../src/Components/Games/GameListCard/stories');
	require('../src/Components/Games/GameProperties/stories');
	require('../src/Components/Games/GamesList/stories');
	require('../src/Components/Games/NoGamesFound/stories');
	require('../src/Components/Games/OpenSpots/stories');
	require('../src/Components/Games/Organizer/stories');
	require('../src/Components/Games/PlayersTabs/stories');
	require('../src/Components/Games/ShareGameButton/stories');
	require('../src/Components/Games/ShareGameButtons/stories');
	require('../src/Components/Layouts/ClosableLayout/stories');
	require('../src/Components/Layouts/FixedBottomLayout/stories');
	require('../src/Components/Layouts/FixedTopLayout/stories');
	require('../src/Components/Onboarding/CitySlide/stories');
	require('../src/Components/Onboarding/OnboardingForm/stories');
	require('../src/Components/PlanGame/InviteOnly/stories');
	require('../src/Components/PlanGame/PlanGameForm/stories');
	require('../src/Components/PlanGame/ShareGameForm/stories');
	require('../src/Components/PlanGame/ShareLink/stories');
	require('../src/Components/PlanGame/SportDateTimeSlide/stories');
	require('../src/Components/PlanGame/SpotSlide/stories');
	require('../src/Components/PlanGame/TitleDescriptionSlide/stories');
	require('../src/Components/Profile/EditProfileForm/stories');
	require('../src/Components/Profile/ProfileDetails/stories');
	require('../src/Components/Profile/ProfileTabs/stories');
	require('../src/Components/Profile/UserMenu/stories');
	require('../src/Components/Profile/UserSpots/stories');
	require('../src/Components/Spots/BackgroundImage/stories');
	require('../src/Components/Spots/SpotAmenities/stories');
	require('../src/Components/Spots/SpotHeader/stories');
	require('../src/Components/Spots/SpotImage/stories');
	require('../src/Components/Spots/SpotLink/stories');
	require('../src/Components/Spots/SpotListCard/stories');
	require('../src/Components/Spots/SpotListCardSmall/stories');
	require('../src/Components/Spots/SpotMap/stories');
	require('../src/Components/Spots/SpotsFilterFlap/stories');
	require('../src/Components/Spots/SpotsList/stories');
	require('../src/Navigation/StackBackHeader/stories');
	require('../src/Screens/Auth/CheckEmailScreen/stories');
	require('../src/Screens/Auth/ConfirmMagicTokenScreen/stories');
	require('../src/Screens/Auth/LoggedOutScreen/stories');
	require('../src/Screens/Auth/LoginScreen/stories');
	require('../src/Screens/Auth/SignupEmailScreen/stories');
	require('../src/Screens/Auth/SignupScreen/stories');
	require('../src/Screens/Debug/DebugScreen/stories');
	require('../src/Screens/Games/CancelGameScreen/stories');
	require('../src/Screens/Games/EditGameScreen/stories');
	require('../src/Screens/Games/GameChatScreen/stories');
	require('../src/Screens/Games/GameDetailsScreen/stories');
	require('../src/Screens/Games/GamesListScreen/stories');
	require('../src/Screens/Games/PlayersListScreen/stories');
	require('../src/Screens/Info/InfoScreen/stories');
	require('../src/Screens/Onboarding/OnboardingScreen/stories');
	require('../src/Screens/Plan/PlanGameScreen/stories');
	require('../src/Screens/Plan/ShareGameScreen/stories');
	require('../src/Screens/Profile/ProfileEditScreen/stories');
	require('../src/Screens/Splash/SplashScreen/stories');
	require('../src/Screens/Spots/SpotsFilterScreen/stories');
	require('../src/Screens/Spots/SpotsListScreen/stories');
}

const stories = [
	'../src/Backgrounds/FieldBackground/stories',
	'../src/Backgrounds/ImageBackground/stories',
	'../src/Backgrounds/LogoHeaderBackground/stories',
	'../src/Components/Auth/LoginEmailForm/stories',
	'../src/Components/Auth/PasscodeForm/stories',
	'../src/Components/Auth/SignupEmailForm/stories',
	'../src/Components/Chat/ChatBubble/stories',
	'../src/Components/Chat/ChatComposer/stories',
	'../src/Components/Chat/ChatDay/stories',
	'../src/Components/Chat/ChatSend/stories',
	'../src/Components/Chat/ChatWithGroup/stories',
	'../src/Components/Common/AbsoluteCenteredActivityIndicator/stories',
	'../src/Components/Common/AlertMsg/stories',
	'../src/Components/Common/Avatar/stories',
	'../src/Components/Common/AvatarPicker/stories',
	'../src/Components/Common/Block/stories',
	'../src/Components/Common/Calendar/stories',
	'../src/Components/Common/CapacityPicker/stories',
	'../src/Components/Common/CapacityPickerField/stories',
	'../src/Components/Common/CenteredActivityIndicator/stories',
	'../src/Components/Common/Checkbox/stories',
	'../src/Components/Common/CityPickerField/stories',
	'../src/Components/Common/ConnectionCheck/stories',
	'../src/Components/Common/DarkFooter/stories',
	'../src/Components/Common/DarkFooterButton/stories',
	'../src/Components/Common/DatePickerField/stories',
	'../src/Components/Common/Divider/stories',
	'../src/Components/Common/DotSpacer/stories',
	'../src/Components/Common/Dropdown/stories',
	'../src/Components/Common/DurationPickerField/stories',
	'../src/Components/Common/Flap/stories',
	'../src/Components/Common/Header/stories',
	'../src/Components/Common/HeaderBtn/stories',
	'../src/Components/Common/Icon/stories',
	'../src/Components/Common/ImageSwiper/stories',
	'../src/Components/Common/InputField/stories',
	'../src/Components/Common/LinkNavigate/stories',
	'../src/Components/Common/LinkOpenURL/stories',
	'../src/Components/Common/Logo/stories',
	'../src/Components/Common/Menu/stories',
	'../src/Components/Common/Modals/CancelConfirmModal/stories',
	'../src/Components/Common/Modals/CapacityPickerModal/stories',
	'../src/Components/Common/Modals/ConfirmModal/stories',
	'../src/Components/Common/Modals/DatePickerModal/stories',
	'../src/Components/Common/Modals/DialogModal/stories',
	'../src/Components/Common/Modals/ImageModal/stories',
	'../src/Components/Common/Modals/Modal/stories',
	'../src/Components/Common/Modals/SportPickerModal/stories',
	'../src/Components/Common/Modals/SpotPickerModal/stories',
	'../src/Components/Common/NavBar/stories',
	'../src/Components/Common/NavBarButton/stories',
	'../src/Components/Common/NavDot/stories',
	'../src/Components/Common/NavDots/stories',
	'../src/Components/Common/NothingFound/stories',
	'../src/Components/Common/OrDivider/stories',
	'../src/Components/Common/RaisedButton/stories',
	'../src/Components/Common/Rating/stories',
	'../src/Components/Common/RoundButton/stories',
	'../src/Components/Common/Row/stories',
	'../src/Components/Common/Slider/stories',
	'../src/Components/Common/SliderWithText/stories',
	'../src/Components/Common/Spacer/stories',
	'../src/Components/Common/SportCard/stories',
	'../src/Components/Common/SportPickerField/stories',
	'../src/Components/Common/SportsList/stories',
	'../src/Components/Common/SpotPickerField/stories',
	'../src/Components/Common/SwitchWithText/stories',
	'../src/Components/Common/Tag/stories',
	'../src/Components/Common/TapsCounter/stories',
	'../src/Components/Common/Text/stories',
	'../src/Components/Common/TextField/stories',
	'../src/Components/Common/TimePickerField/stories',
	'../src/Components/Games/AdminMenu/stories',
	'../src/Components/Games/Attendees/stories',
	'../src/Components/Games/CancelGameForm/stories',
	'../src/Components/Games/ClickableAttendees/stories',
	'../src/Components/Games/DescriptionReadMore/stories',
	'../src/Components/Games/EditGameForm/stories',
	'../src/Components/Games/GameCanceledFlag/stories',
	'../src/Components/Games/GameDetails/stories',
	'../src/Components/Games/GameListCard/stories',
	'../src/Components/Games/GameProperties/stories',
	'../src/Components/Games/GamesList/stories',
	'../src/Components/Games/NoGamesFound/stories',
	'../src/Components/Games/OpenSpots/stories',
	'../src/Components/Games/Organizer/stories',
	'../src/Components/Games/PlayersTabs/stories',
	'../src/Components/Games/ShareGameButton/stories',
	'../src/Components/Games/ShareGameButtons/stories',
	'../src/Components/Layouts/ClosableLayout/stories',
	'../src/Components/Layouts/FixedBottomLayout/stories',
	'../src/Components/Layouts/FixedTopLayout/stories',
	'../src/Components/Onboarding/CitySlide/stories',
	'../src/Components/Onboarding/OnboardingForm/stories',
	'../src/Components/PlanGame/InviteOnly/stories',
	'../src/Components/PlanGame/PlanGameForm/stories',
	'../src/Components/PlanGame/ShareGameForm/stories',
	'../src/Components/PlanGame/ShareLink/stories',
	'../src/Components/PlanGame/SportDateTimeSlide/stories',
	'../src/Components/PlanGame/SpotSlide/stories',
	'../src/Components/PlanGame/TitleDescriptionSlide/stories',
	'../src/Components/Profile/EditProfileForm/stories',
	'../src/Components/Profile/ProfileDetails/stories',
	'../src/Components/Profile/ProfileTabs/stories',
	'../src/Components/Profile/UserMenu/stories',
	'../src/Components/Profile/UserSpots/stories',
	'../src/Components/Spots/BackgroundImage/stories',
	'../src/Components/Spots/SpotAmenities/stories',
	'../src/Components/Spots/SpotHeader/stories',
	'../src/Components/Spots/SpotImage/stories',
	'../src/Components/Spots/SpotLink/stories',
	'../src/Components/Spots/SpotListCard/stories',
	'../src/Components/Spots/SpotListCardSmall/stories',
	'../src/Components/Spots/SpotMap/stories',
	'../src/Components/Spots/SpotsFilterFlap/stories',
	'../src/Components/Spots/SpotsList/stories',
	'../src/Navigation/StackBackHeader/stories',
	'../src/Screens/Auth/CheckEmailScreen/stories',
	'../src/Screens/Auth/ConfirmMagicTokenScreen/stories',
	'../src/Screens/Auth/LoggedOutScreen/stories',
	'../src/Screens/Auth/LoginScreen/stories',
	'../src/Screens/Auth/SignupEmailScreen/stories',
	'../src/Screens/Auth/SignupScreen/stories',
	'../src/Screens/Debug/DebugScreen/stories',
	'../src/Screens/Games/CancelGameScreen/stories',
	'../src/Screens/Games/EditGameScreen/stories',
	'../src/Screens/Games/GameChatScreen/stories',
	'../src/Screens/Games/GameDetailsScreen/stories',
	'../src/Screens/Games/GamesListScreen/stories',
	'../src/Screens/Games/PlayersListScreen/stories',
	'../src/Screens/Info/InfoScreen/stories',
	'../src/Screens/Onboarding/OnboardingScreen/stories',
	'../src/Screens/Plan/PlanGameScreen/stories',
	'../src/Screens/Plan/ShareGameScreen/stories',
	'../src/Screens/Profile/ProfileEditScreen/stories',
	'../src/Screens/Splash/SplashScreen/stories',
	'../src/Screens/Spots/SpotsFilterScreen/stories',
	'../src/Screens/Spots/SpotsListScreen/stories'
];

module.exports = {
  loadStories,
  stories,
};
